### PR TITLE
Real activaton

### PR DESCRIPTION
**Pull request by mattangus**
Main things implemented.

### Tensor
- element wise functor operations
- `operator<math>=` variants (`+=` etc.)

### Activation
- all elementwise activations forward and backward

### misc
- `operator<<` for easy printing.

### CODE REVIEW

**Comment by mElBalkini** [comment]
Looks good to me. I like the oprator overloads.
However, I couldn't build the latest commit in here.
Did you see this error before?
```
xenon@HP-ENVY:~/repos/darknet/build$ cmake ../cpp_src/
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found GTest: /usr/lib/libgtest.a
-- Found CUDAToolkit: /usr/local/cuda-10.2/include (found version "10.2.89")
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-10.2 (found version "10.2")
-- Autodetected CUDA architecture(s):  3.5
cuda falgs: -gencodearch=compute_35,code=sm_35
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xenon/repos/darknet/build
xenon@HP-ENVY:~/repos/darknet/build$ make
[ 12%] Building NVCC (Device) object CMakeFiles/runTests2.dir/gpu/runTests2_generated_dark.cu.o
[ 25%] Building NVCC (Device) object CMakeFiles/runTests2.dir/gpu/runTests2_generated_tensor.cu.o
/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(18): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::plus<_Tp>::operator()(_Tp &, _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::plus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::plus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(18): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::plus<_Tp>::operator()(_Tp &, _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::plus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::plus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(27): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::minus<_Tp>::operator()(const _Tp &, const _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::minus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::minus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(27): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::minus<_Tp>::operator()(const _Tp &, const _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::minus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::minus<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(36): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::divides<_Tp>::operator()(const _Tp &, const _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::divides<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::divides<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(36): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::divides<_Tp>::operator()(const _Tp &, const _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::divides<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::divides<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(45): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::multiplies<_Tp>::operator()(const _Tp &, const _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::multiplies<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::multiplies<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

/home/xenon/repos/darknet/cpp_src/./gpu/tensor.hpp(45): error: more than one conversion function from "const half" to a built-in type applies:
            function "__half::operator float() const"
            function "__half::operator short() const"
            function "__half::operator unsigned short() const"
            function "__half::operator int() const"
            function "__half::operator unsigned int() const"
            function "__half::operator long long() const"
            function "__half::operator unsigned long long() const"
            function "__half::operator __nv_bool() const"
          detected during:
            instantiation of "_Tp darknet::gpu::multiplies<_Tp>::operator()(const _Tp &, const _Tp &) const [with _Tp=half]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(86): here
            instantiation of "void darknet::kernel::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::multiplies<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(157): here
            instantiation of "void darknet::gpu::elementwise<T,F>(T *, size_t, T) [with T=half, F=darknet::gpu::multiplies<half>]"
/home/xenon/repos/darknet/cpp_src/gpu/tensor.cu(169): here

8 errors detected in the compilation of "/tmp/tmpxft_00006af3_00000000-6_tensor.cpp1.ii".
CMake Error at runTests2_generated_tensor.cu.o.cmake:276 (message):
  Error generating file
  /home/xenon/repos/darknet/build/CMakeFiles/runTests2.dir/gpu/./runTests2_generated_tensor.cu.o


CMakeFiles/runTests2.dir/build.make:82: recipe for target 'CMakeFiles/runTests2.dir/gpu/runTests2_generated_tensor.cu.o' failed
make[2]: *** [CMakeFiles/runTests2.dir/gpu/runTests2_generated_tensor.cu.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/runTests2.dir/all' failed
make[1]: *** [CMakeFiles/runTests2.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mattangus** [comment]
Oh yeah, I've seen this a ton. I can't remember the fix off the top of my head.  I'll look into it.

**Comment by mattangus** [comment]
What's the output of the `cmake` command. There should be 2 lines like:

```
-- Autodetected CUDA architecture(s):  7.5
cuda falgs: -gencodearch=compute_75,code=sm_75
```

It could be that your GPU doesn't support fp16.

**Comment by mElBalkini** [comment]
Yeah, It is an old laptop. I don't think it has fp16 cuda support.
Anyway, the pull request looks good to merge. I will try to fix this error, or switch to my main workstation.

**Comment by chh7411898** [comment]
hi did you sovle the bug ?

**Pull request merged**
